//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipShip
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletedOrder
    {
        public int Id { get; set; }
        public string OrderName { get; set; }
        public string OrderCountry { get; set; }
        public string TravellerName { get; set; }
        public string ShopperName { get; set; }
        public string ImagePath { get; set; }
        public string TravellerId { get; set; }
        public string ShopperId { get; set; }
    }
}
