//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipShip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public Nullable<int> OrderId { get; set; }
        public string SelectedBy { get; set; }
        public int id { get; set; }
    }
}
