//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipShip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Quantity { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<long> DealPrice { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public string Status { get; set; }
        public string ImagePath { get; set; }
        public string Country { get; set; }
        public string Brand { get; set; }
    }
}
